name: Validate (ocsf-validator)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    name: Validate the schema
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set colorized output
      shell: bash
      run: echo "TERM=xterm" >> $GITHUB_ENV

    - name: Install validator
      shell: bash
      run: python -m pip install 'ocsf-validator>=0.1.1,<0.2'

    - name: Run validator
      shell: bash
      run: python -m ocsf_validator .
